spring:
  application:
    name: student-grade-system
  
  # 环境配置
  profiles:
    active: dev
  
  # 数据源配置
  datasource:
    url: jdbc:mysql://47.103.36.20:3306/school_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: snemc.mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Redis配置
  data:
    redis:
      host: 47.103.36.20
      port: 6379
      password: snemc.redis.6039
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: -1ms
  
  # Jackson配置
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB
      file-size-threshold: 2KB

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# Knife4j配置
knife4j:
  enable: true
  openapi:
    title: 学生成绩管理系统API
    description: 学生成绩管理系统的RESTful API文档
    version: 1.0.0
    contact:
      name: ljp
      email: ljp@example.com
  setting:
    language: zh_cn
    enable-version: true
    enable-reload-cache-parameter: true
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false

# JWT配置
app:
  jwt:
    secret: mySecretKey123456789012345678901234567890abcdefghijklmnopqrstuvwxyz
    expiration: 86400 # 24小时（秒）
    refresh-expiration: 604800 # 7天（秒）
  
  # 文件上传配置
  file:
    upload-path: ./uploads
    max-size: 5MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 日志配置
logging:
  level:
    com.ljp.xjt: DEBUG
    org.springframework.security: DEBUG
    com.baomidou.mybatisplus: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/student-system.log
    max-size: 100MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.ljp.xjt: DEBUG
    org.springframework.security: DEBUG

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.ljp.xjt: INFO
    org.springframework.security: INFO

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    com.ljp.xjt: INFO 